STORE_OPEN_TIME = "18:00"
STORE_CLOSE_TIME = "21:00"

LOW_THRESHOLD_MIN = 30
MEDIUM_THRESHOLD_MIN = 60

RECOGNITION_INTERVAL_SEC = 5
CURRENTLY_DETECTED_TIMEOUT_SEC = 10

UNKNOWN_STREAK_THRESHOLD = 2

ALERT_DEDUPE_WINDOW_SEC = 60

CAMERAS = [
    {"id": "cam1", "name": "201 Door", "source": "rtsp://admin:FWXDNE@192.168.1.6:554/Streaming/Channels/102", "location": "front"},
]

CAMERA_OFFLINE_THRESHOLD_SEC = 30
CAMERA_HEALTH_CHECK_INTERVAL_SEC = 15

TAMPER_BRIGHTNESS_THRESHOLD = 15
TAMPER_VARIANCE_THRESHOLD = 5