STORE_OPEN_TIME = "18:00"
STORE_CLOSE_TIME = "21:00"

LOW_THRESHOLD_MIN = 30
MEDIUM_THRESHOLD_MIN = 60

RECOGNITION_INTERVAL_SEC = 10
CURRENTLY_DETECTED_TIMEOUT_SEC = 30
UNKNOWN_STREAK_THRESHOLD = 2

ALERT_DEDUPE_WINDOW_SEC = 120

import os
from dotenv import load_dotenv
load_dotenv()
CAMERAS = [
    {"id": "cam1", "name": "201 Door", "source": os.getenv("CAM1_RTSP_URL", ""), "location": "front"},
    {"id": "cam2", "name": "201 Room", "source": os.getenv("CAM2_RTSP_URL", ""), "location": "front"},
]

CAMERA_OFFLINE_THRESHOLD_SEC = 30
CAMERA_HEALTH_CHECK_INTERVAL_SEC = 15
CAMERA_HEARTBEAT_INTERVAL_SEC = 5

TAMPER_BRIGHTNESS_THRESHOLD = 10
TAMPER_VARIANCE_THRESHOLD = 5

ESCALATION_CHECK_INTERVAL_SEC = 60
ESCALATION_LOW_TO_MEDIUM_SEC = 1800   # 30 min unacknowledged
ESCALATION_MEDIUM_TO_HIGH_SEC = 3600  # 60 min unacknowledged

SNAPSHOT_RETENTION_DAYS = 30